language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
install: pip install -r requirements.txt --upgrade pip
script:
    - python -m flake8
    - python -m pytest
branches:
    only:
        - master
        - development
jobs:
  include:
    python: "3.8"
    services:
        - docker
    install: pip install -r requirements.txt --upgrade pip
    before_script:
        - docker pull $DOCKER_USERNAME/ifpass || true
    script:
        - python -m flake8
        - python -m pytest
        - docker build --pull --cache-from $DOCKER_USERNAME/ifpass --tag $DOCKER_USERNAME/ifpass .
    after_script:
        - docker images
    before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/ifpass
    deploy:
      provider: script
      script: aws cloudformation deploy --stack-name=ifpass --template-file=aws/public_vpc.yml --capabilities=CAPABILITY_IAM && \
              aws cloudformation deploy --stack-name=ifpass --template-file=aws/public_service.yml --capabilities=CAPABILITY_IAM && \
              aws cloudformation describe-stacks --stack-name production | grep elb.amazonaws.com
      on:
        branch: master
